# Generated by Django 3.2.3 on 2023-03-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200)),
                ('field_with_under_score', models.IntegerField()),
                ('fieldWithUpperCase', models.IntegerField()),
                ('fieldWith_Case', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200)),
                ('field_with_under_score', models.IntegerField()),
                ('fieldWithUpperCase', models.IntegerField()),
                ('fieldWith_Case', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCase3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200, null=True)),
                ('field2', models.IntegerField(null=True)),
                ('field3', models.BigIntegerField(null=True)),
                ('field4', models.BinaryField(null=True)),
                ('field5', models.FloatField(null=True)),
                ('field6', models.TextField(null=True)),
                ('field7', models.TimeField(null=True)),
                ('field8', models.DateTimeField(null=True)),
                ('field10', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.model2')),
                ('field11', models.ManyToManyField(to='testapp.Model3')),
                ('field9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.model1')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCase2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200)),
                ('field2', models.IntegerField()),
                ('field3', models.BigIntegerField()),
                ('field4', models.BinaryField()),
                ('field5', models.FloatField()),
                ('field6', models.TextField()),
                ('field7', models.TimeField()),
                ('field8', models.DateTimeField()),
                ('field10', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.model2')),
                ('field11', models.ManyToManyField(to='testapp.Model3')),
                ('field9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.model1')),
            ],
        ),
    ]
